# Generated by Django 3.1.1 on 2020-09-04 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('residence', models.CharField(max_length=255, verbose_name='Residencia')),
                ('tel_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('sex', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10, verbose_name='Sexo')),
                ('curp', models.CharField(max_length=50, verbose_name='Curp')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-curp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('residence', models.CharField(max_length=255, verbose_name='Residencia')),
                ('tel_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('sex', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10, verbose_name='Sexo')),
                ('curp', models.CharField(max_length=50, verbose_name='Curp')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('age', models.PositiveIntegerField(verbose_name='Edad')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateField(auto_now=True, verbose_name='Actualizado')),
                ('cedula', models.CharField(max_length=30, verbose_name='Cédula')),
                ('universidad', models.CharField(max_length=250, verbose_name='Universidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-curp'],
                'abstract': False,
            },
        ),
    ]
