# Generated by Django 3.1.1 on 2020-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cel_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cel_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tel_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
