# Generated by Django 3.1.1 on 2020-09-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200905_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('category', models.CharField(choices=[('General', 'General'), ('Embarazo', 'Embarazo'), ('Otra', 'Otra')], max_length=50, verbose_name='Categoría')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient', verbose_name='Paciente')),
            ],
        ),
    ]
